name: channel
description: Golang like send/receive communication channel with multi-listen capability
version: 2.0.1
homepage: https://github.com/desktop-dart/channel

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
