name: channel
description: Golang like send/receive communication channel with multi-listen capability
version: 2.0.2
homepage: https://github.com/desktop-dart/channel

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
